#!/usr/bin/with-contenv bash

JAVA_ARGS_FILE="$CONFIG_DIR/java.vmoptions"


if [ ! -f "$JAVA_ARGS_FILE" ]; then
    echo "Init java vm options. $JAVA_ARGS_FILE"
    mkdir -p "$CONFIG_DIR"
    cp /defaults/biglybt/java.vmoptions $JAVA_ARGS_FILE
fi
