#!/usr/bin/with-contenv bash

WEBUI_PORT="${WEBUI_PORT:=9091}"
WEBUI_USER="${WEBUI_USER:=admin}"
WEBUI_PASSWD="${WEBUI_PASSWD:=admin}"

# 不可变
WEBUI_DIR="/webui"
WEBUI_PLUGIN_DIR="/config/.biglybt/plugins/xmwebui/"
WEBUI_PLUGIN_FILE="/plugins/xmwebui.zip"


if [ ! -d "$WEBUI_PLUGIN_DIR" ]; then
    mkdir -p "$WEBUI_PLUGIN_DIR"
    unzip "$WEBUI_PLUGIN_FILE" -d "$WEBUI_PLUGIN_DIR"

    # 使用 biglybt --ui=console 设置插件配置
    biglybt --ui=console << EOF
set "Plugin.xmwebui.xmwebui.web.dir" "$WEBUI_DIR" string
quit
EOF

fi


# 设置端口、WEB用户&密码
biglybt --ui=console << EOF
set "Plugin.xmwebui.Port" $WEBUI_PORT int
set "Plugin.xmwebui.User" "$WEBUI_USER" string
set "Plugin.xmwebui.Password Enable" true boolean
set "Plugin.xmwebui.Password" "$WEBUI_PASSWD" password
quit
EOF
